---
    version: '2'
    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:7.2.2
        hostname: zookeeper
        container_name: zookeeper
        ports:
          - "2181:2181"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
    
      broker0:
        image: confluentinc/cp-server:7.2.2
        hostname: broker0
        container_name: broker0
        depends_on:
          - zookeeper
        ports:
          - "9092:9092"
          - "8090:8090"
        volumes:
          - .:/host
        environment:
          KAFKA_BROKER_ID: 0
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker0:29092,PLAINTEXT_HOST://localhost:9092
          KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 3
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
          KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker0:29092
          KAFKA_CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
          KAFKA_CONFLUENT_METRICS_ENABLE: 'true'
          KAFKA_CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
          KAFKA_KAFKA_REST_ADVERTISED_LISTENERS: http://localhost:8090
          KAFKA_CONFLUENT_BALANCER_ENABLE: 'true'
          KAFKA_CONFLUENT_BALANCER_HEAL_UNEVEN_LOAD_TRIGGER: ANY_UNEVEN_LOAD
          KAFKA_CONFLUENT_BALANCER_HEAL_BROKER_FAILURE_THRESHOLD_MS: 5000
    
      broker1:
        image: confluentinc/cp-server:7.2.2
        hostname: broker1
        container_name: broker1
        depends_on:
          - zookeeper
        ports:
          - "9192:9192"
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29192,PLAINTEXT_HOST://localhost:9192
          KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 3
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
          KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker0:29092
          KAFKA_CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
          KAFKA_CONFLUENT_METRICS_ENABLE: 'true'
          KAFKA_CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
          KAFKA_CONFLUENT_BALANCER_ENABLE: 'true'
          KAFKA_CONFLUENT_BALANCER_HEAL_UNEVEN_LOAD_TRIGGER: ANY_UNEVEN_LOAD
          KAFKA_CONFLUENT_BALANCER_HEAL_BROKER_FAILURE_THRESHOLD_MS: 5000
    
      broker2:
        image: confluentinc/cp-server:7.2.2
        hostname: broker2
        container_name: broker2
        depends_on:
          - zookeeper
        ports:
          - "9292:9292"
        environment:
          KAFKA_BROKER_ID: 2
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:29292,PLAINTEXT_HOST://localhost:9292
          KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 3
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
          KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker0:29092
          KAFKA_CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
          KAFKA_CONFLUENT_METRICS_ENABLE: 'true'
          KAFKA_CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
          KAFKA_CONFLUENT_BALANCER_ENABLE: 'true'
          KAFKA_CONFLUENT_BALANCER_HEAL_UNEVEN_LOAD_TRIGGER: ANY_UNEVEN_LOAD
          KAFKA_CONFLUENT_BALANCER_HEAL_BROKER_FAILURE_THRESHOLD_MS: 5000
    
      control-center:
        image: confluentinc/cp-enterprise-control-center:7.2.2
        hostname: control-center
        container_name: control-center
        depends_on:
          - zookeeper
          - broker0
        ports:
          - "9021:9021"
        environment:
          CONTROL_CENTER_BOOTSTRAP_SERVERS: broker0:29092
          CONTROL_CENTER_STREAMS_CPREST_URL: broker0:8090
          CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
          CONTROL_CENTER_REPLICATION_FACTOR: 3
          CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
          CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
          CONFLUENT_METRICS_TOPIC_REPLICATION: 3
          PORT: 9021