---
version: '2'
services:
  zookeeper3:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper3
    container_name: zookeeper3
    networks:
      - kafka3_network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - "zookeeper3_data:/var/lib/zookeeper/data"
      - "zookeeper3_logs:/var/lib/zookeeper/log"

  kafka3_broker_1:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka3_broker_1
    container_name: kafka3_broker_1
    depends_on:
      - zookeeper3
    networks:
      - kafka3_network
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper3:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3_broker_1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - "kafka3_broker_1_data:/var/lib/kafka/data"

  kafka3_broker_2:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka3_broker_2
    container_name: kafka3_broker_2
    depends_on:
      - zookeeper3
    networks:
      - kafka3_network
    ports:
      - "29093:29093"
      - "9093:9093"
      - "9201:9201"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper3:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3_broker_2:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9201
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - "kafka3_broker_2_data:/var/lib/kafka/data"

  kafka3_broker_3:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka3_broker_3
    container_name: kafka3_broker_3
    depends_on:
      - zookeeper3
    networks: 
      - kafka3_network
    ports:
      - "29094:29094"
      - "9094:9094"
      - "9301:9301"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper3:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3_broker_3:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9301
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - "kafka3_broker_3_data:/var/lib/kafka/data"

networks:
  kafka3_network:
    external: true
volumes:
  zookeeper3_data:
    driver: local
  zookeeper3_logs:
    driver: local
  kafka3_broker_1_data:
    driver: local
  kafka3_broker_2_data:
    driver: local
  kafka3_broker_3_data:
    driver: local

